version: "3.9"

services:
  db:
    image: postgres:15
    container_name: balkan-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: balkan_storage
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d balkan_storage"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: balkan-backend
    restart: always
    environment:
      PORT: 8080
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: balkan_storage
      JWT_SECRET: supersecret
      STORAGE_PATH: /data/storage
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - backend_data:/data/storage

  frontend:
    build: ./frontend
    container_name: balkan-frontend
    restart: always
    environment:
      NEXT_PUBLIC_API_URL: http://backend:8080
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  db_data:
  backend_data: