
FROM golang:1.22.5-alpine AS builder


RUN apk update && apk upgrade --no-cache && apk add --no-cache git

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download


COPY . .

RUN go build -o backend ./main.go

FROM alpine:3.19

RUN apk update && apk upgrade --no-cache && apk add --no-cache ca-certificates

WORKDIR /root/
COPY --from=builder /app/backend .

EXPOSE 8080

CMD ["./backend"]