DROP TABLE IF EXISTS audit_logs;
ALTER TABLE files DROP COLUMN IF EXISTS trashed;
ALTER TABLE files DROP COLUMN IF EXISTS trashed_at;
ALTER TABLE folders DROP COLUMN IF EXISTS trashed;
ALTER TABLE folders DROP COLUMN IF EXISTS trashed_at;