ALTER TABLE files DROP CONSTRAINT IF EXISTS filename_length;
ALTER TABLE folders DROP CONSTRAINT IF EXISTS foldername_length;
ALTER TABLE users DROP CONSTRAINT IF EXISTS username_length;
ALTER TABLE users DROP CONSTRAINT IF EXISTS email_length;
DROP TABLE IF EXISTS file_versions;
ALTER TABLE users DROP COLUMN IF EXISTS role;
DROP TABLE IF EXISTS audit_logs;